### PR TITLE
Component Patterns

### PR DESCRIPTION
**Pull request by PrincAm**
Hi! 

I've added exercises for upcoming workshop. 

There are covered 4 patterns: Render props, HOC, Compound component and Controlled components. Every pattern has own folder with lecture and exercise projects (and their final solutions). I plan to complete lecture first and then attendees the exercise where are applied similar principles. Let's see what we will finish.

It isn't final version. I will continue to work on an update of README, the presentation itself and code revision.

(Don't spend too much time on review, it doesn't have to be perfect.)

### CODE REVIEW

**Comment by Aprillion** [comment]
* https://github.com/msd-code-academy/react-workshop/blob/45bdb9e134505736de5b5bd70951547b9a8ce209/02-component-patterns/exercises/compound-components/exercise/src/
Maybe few words about what is a "Stepper" in App.js + `className="stepper-controls"` would be useful in the Stepper.js

**Comment by Aprillion** [comment]
* https://github.com/msd-code-academy/react-workshop/blob/45bdb9e134505736de5b5bd70951547b9a8ce209/02-component-patterns/exercises/higher-order-components/exercise/src

`import hoistStatics` sounds very mysterious - if it will be needed in the solution, why it's not needed in the "previous" version? I thought it would be just refactoring task, not adding new features yet...

**Comment by Aprillion** [comment]
https://github.com/msd-code-academy/react-workshop/blob/45bdb9e134505736de5b5bd70951547b9a8ce209/02-component-patterns/exercises/controlled-components/exercise/src/

controlled-component starting point is the compound-component on purpose and not by accident? it looks a bit confusing (since compound components are more advanced IMHO, is the task to simplify it because the extra features are not needed?)

**Review by Aprillion — APPROVED** [review]

**Comment by PrincAm** [comment]
@Aprillion thanks for having a look. What is `Stepper` will be clear if they run the app but I will explain it and add a comment. `hoistStatics` is needed to copy statics from child to parent, i will comment it as well. Controlled Component exercise really starts from the point where Compound Component exercise finished. it will be the last chapter, more less easy one. another PR will follow

**Pull request merged**
